site_name: Universe Roleplay - Wetboek & Regelgeving
site_url: https://sitename.example
site_description: Officiële wet- en regelgeving van Universe Roleplay
site_author: Universe Roleplay

theme:
  name: material
  language: nl
  font:
    text: Merriweather
    code: JetBrains Mono
  icon:
    logo: material/scale-balance
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Donkere modus inschakelen
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Lichte modus inschakelen
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: false
      toc_depth: 2-3

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Wetboek & Regelgeving:
      - Strafrecht:
          - Wetboek van Strafrecht Universe: WSRU.md
      - Bijzondere wetten:
          - Wet wapens en munitie Universe: WWMU.md
          - Opiumwet Universe: OWU.md
      - Verkeer:
          - Wegenverkeerswet Universe: WVWU.md
      - Lokale regelgeving:
          - Algemene Plaatselijke Verordening Universe: APV Universe.md